### PR TITLE
GDB-7827 Fix inconsistent cluster defaults on creation

### PR DESCRIPTION
**Pull request by vasilnv**
Update defaults for minimum election timeout and for election range timeout

### CODE REVIEW

**Review by yordanalexandrov — APPROVED** [review]

**Comment by vasilnv** [comment]
Jenkins retry build

**Comment by vasilnv** [comment]
Jenkins retry build

**Comment by yordanalexandrov** [comment]
Jenkins retry build

**Comment by vasilnv** [comment]
Jenkins retry build

**Pull request merged**
