### PR TITLE
Gdb 6448 fix warn users when they unset their password master 1.11

### PR DESCRIPTION
**Pull request by IvanovaD**
Cherry-picked changes from fixing cypress tests on warning users when they unset their password

### CODE REVIEW

**Comment by desislava-hristova-ontotext** [comment]
Jenkins retry build

**Comment by IvanovaD** [comment]
Jenkins retry build

**Comment by IvanovaD** [comment]
Jenkins retry build

**Comment by IvanovaD** [comment]
Jenkins retry build

**Comment by IvanovaD** [comment]
Jenkins retry build

**Comment by IvanovaD** [comment]
Jenkins retry build

**Review by desislava-hristova-ontotext — APPROVED** [review]

**Pull request merged**
