### PR TITLE
GDB-10926: TTYG View is Broken After Production Build

### PR DESCRIPTION
**Pull request by boyan-tonchev**
## What
- All icons are not displayed;
- The readableTimestamp filter has issues (in production build only);
- All CSS links in TTYG templates are broken.

## Why
- We use the paid package "@awesome.me/kit-94ffd2fc4a" and have an authentication token. However, for some reason, the CSS classes are not imported into the output vendor.js file, despite adding the required configuration as explained [here](https://docs.fontawesome.com/web/setup/packages);
- The filter was not injected properly;
- All links are version-dependent, and the version string was not correctly replaced during the build process.

## How
- Copied the necessary files after installation and modified vendor.js to use them;
- Moved the functionality that transforms the date timestamp to a human-readable string into the main TTYG controller;
- Added a "replaceVersion" transformation to all TTYG templates during the build process.

### CODE REVIEW

**Review by yordanalexandrov — APPROVED** [review]

**Comment by boyan-tonchev** [comment]
Jenkins retry build

**Comment by boyan-tonchev** [comment]
Jenkins retry build

**Comment by boyan-tonchev** [comment]
Jenkins retry build

**Comment by boyan-tonchev** [comment]
Jenkins retry build

**Pull request merged**
