### PR TITLE
GDB-8602 sparql view visual improvements

### PR DESCRIPTION
**Pull request by svilenvelikov**
## What
Fixes the page heading which used to show wrong label and had missing info button, fixed the yasr results height and various other styling issues in the yasgui.

## Why
The look and feel of the sparql view needs to be improved and to be more aligned with the old one.

## How
* Fix the yasr results table height wrongly applied globally instead only to results rendered in the similarity index creation page.
* Removed obsolete sparql view heading label and use the original one.
* Add back the proper heading to the sparql view.
* Fix multiple styling issues in the sparql view: properly position and resize the toolbar buttons, properly align the yasgui components when changing the layout, reposition the keyboard shortcuts trigger button to fit properly in the yasqe window, etc.

### CODE REVIEW

**Review by boyan-tonchev — DISMISSED** [review]

**Comment by svilenvelikov** [comment]
Jenkins retry build

**Comment by svilenvelikov** [comment]
Jenkins retry build

**Comment by svilenvelikov** [comment]
Jenkins retry build

**Comment by svilenvelikov** [comment]
Jenkins retry build

**Review by boyan-tonchev — APPROVED** [review]

**Pull request merged**
