### PR TITLE
GDB-8369 cherry pick into 2.2

### PR DESCRIPTION
**Pull request by Emskiqq**
(cherry picked from commit da8347379a2a1cb5294ee79b76504c9b2dab0521)

### CODE REVIEW

**Review by yordanalexandrov — APPROVED** [review]

**Comment by Emskiqq** [comment]
Jenkins retry build

**Comment by Emskiqq** [comment]
Jenkins retry build

**Comment by Emskiqq** [comment]
Jenkins retry build

**Comment by Emskiqq** [comment]
Jenkins retry build

**Pull request merged**
