### PR TITLE
GDB-10913 - On failed import, hide the invalid timestamp in the status info

### PR DESCRIPTION
**Pull request by DesiBorisova**
## What?
When a file import fails, an incorrect timestamp will not be displayed in the status info dialog. In this case, the timestamp will be hidden.

## Why?
The back-end returns "0" for `importedOn` in the case of a failed import. This incorrectly gets filtered into a date.

## How?
I added a condition to show the date only if it's defined.

## Screenshots?
Screenshot from 2024-10-02 17-39-50

### CODE REVIEW

**Review by svilenvelikov — APPROVED** [review]

**Comment by DesiBorisova** [comment]
Jenkins retry build

**Comment by svilenvelikov** [comment]
Jenkins retry build

**Comment by svilenvelikov** [comment]
Jenkins retry build

**Comment by svilenvelikov** [comment]
Jenkins retry build

**Pull request merged**
