### PR TITLE
Gdb 6448 fix warn users when they unset their password master

### PR DESCRIPTION
**Pull request by IvanovaD**
Last and working version of the fixed cypress test for warning when creating user. Also, after all toggles security to OFF

### CODE REVIEW

**Comment by IvanovaD** [comment]
Jenkins retry build

**Comment by IvanovaD** [comment]
Jenkins retry build

**Comment by IvanovaD** [comment]
Jenkins retry build

**Comment by IvanovaD** [comment]
Jenkins retry build

**Comment by IvanovaD** [comment]
Jenkins retry build

**Review by desislava-hristova-ontotext — APPROVED** [review]

**Pull request merged**
