### PR TITLE
GDB-7305-Cypress test for CRUD of saved graphs.

### PR DESCRIPTION
**Pull request by MartinaDimova**

### CODE REVIEW

**Comment by MartinaDimova** [comment]
Jenkins retry build

**Comment by MartinaDimova** [comment]
Jenkins retry build

**Comment by MartinaDimova** [comment]
Jenkins retry build

**Comment by MartinaDimova** [comment]
Jenkins retry build

**Comment by MartinaDimova** [comment]
Jenkins retry build

**Comment by MartinaDimova** [comment]
Jenkins retry build

**Review by boyan-tonchev — DISMISSED** [review]

**Review by boyan-tonchev — APPROVED** [review]

**Pull request merged**
