### PR TITLE
Gdb 6764 internationalization acceptance tests in workbench

### PR DESCRIPTION
**Pull request by sava-savov-ontotext**

### CODE REVIEW

**Review by yordanalexandrov — DISMISSED** [review]

**Comment by yordanalexandrov** [comment]
Jenkins retry build

**Comment by yordanalexandrov** [comment]
Jenkins retry build

**Review by yordanalexandrov — APPROVED** [review]
LGTM

**Comment by sava-savov-ontotext** [comment]
Jenkins retry build

**Review by yordanalexandrov — APPROVED** [review]
LGTM

**Pull request merged**
