### PR TITLE
GDB-6448 Fix Warn users when they unset the password Master

### PR DESCRIPTION
**Pull request by IvanovaD**
Added warning  when creating admin user and when editing admin user through Users and Access
Added cypress tests for both cases

### CODE REVIEW

**Comment by IvanovaD** [comment]
Jenkins retry build

**Review by desislava-hristova-ontotext — APPROVED** [review]

**Comment by desislava-hristova-ontotext** [comment]
Jenkins retry build

**Comment by desislava-hristova-ontotext** [comment]
Jenkins retry build

**Comment by desislava-hristova-ontotext** [comment]
Jenkins retry build

**Comment by IvanovaD** [comment]
Jenkins retry build

**Comment by IvanovaD** [comment]
Jenkins retry build

**Comment by IvanovaD** [comment]
Jenkins retry build

**Comment by IvanovaD** [comment]
Jenkins retry build

**Pull request merged**
