### PR TITLE
Fix visual graph searchForResource test.

### PR DESCRIPTION
**Pull request by IvanovaD**

### CODE REVIEW

**Review by sava-savov-ontotext — APPROVED** [review]

**Comment by IvanovaD** [comment]
Jenkins retry build

**Comment by sava-savov-ontotext** [comment]
Jenkins retry build

**Comment by IvanovaD** [comment]
Jenkins retry build

**Comment by IvanovaD** [comment]
Jenkins retry build

**Review by sava-savov-ontotext — APPROVED** [review]

**Pull request merged**
