### PR TITLE
GDB-7302-Incomplete error message when you try to query disabled plugin

### PR DESCRIPTION
**Pull request by MartinaDimova**
Fixed customError message when disabled plugin is called.

### CODE REVIEW

**Comment by MartinaDimova** [comment]
Jenkins retry build

**Review by svilenvelikov — APPROVED** [review]

**Comment by MartinaDimova** [comment]
Jenkins retry build

**Comment by MartinaDimova** [comment]
Jenkins retry build

**Comment by MartinaDimova** [comment]
Jenkins retry build

**Pull request merged**
