### PR TITLE
GDB-7711: Extend table plugin

### PR DESCRIPTION
**Pull request by boyan-tonchev**
What?
Integrate the extended table yasr plugin.

Why?
There is a custom cell formatting in WB table yasr plugin. All resource are present with short uri and every one has a button to copy link resource.

How?
Update version of ontotext-yasgui-web-component

### CODE REVIEW

**Comment by boyan-tonchev** [comment]
Jenkins retry build

**Comment by boyan-tonchev** [comment]
Jenkins retry build

**Comment by boyan-tonchev** [comment]
Jenkins retry build

**Comment by boyan-tonchev** [comment]
Jenkins retry build

**Comment by boyan-tonchev** [comment]
Jenkins retry build

**Comment by boyan-tonchev** [comment]
Jenkins retry build

**Comment by boyan-tonchev** [comment]
Jenkins retry build

**Comment by boyan-tonchev** [comment]
Jenkins retry build

**Review by svilenvelikov — APPROVED** [review]

**Pull request merged**
