### PR TITLE
GDB-5250 No schema vis graph setting

### PR DESCRIPTION
**Pull request by desislava-hristova-ontotext**
Add no schema toggle to vis graph settings. Add default value for this toggle in user settings

### CODE REVIEW

**Comment by desislava-hristova-ontotext** [comment]
Jenkins retry build

**Comment by desislava-hristova-ontotext** [comment]
All tests have passed locally on my machine against GDB 9.7.0-bootstrap1

**Review by avataar — APPROVED** [review]

**Comment by avataar** [comment]
Jenkins please retry a build

**Comment by avataar** [comment]
Jenkins retry build

**Comment by desislava-hristova-ontotext** [comment]
Jenkins retry build

**Pull request merged**
