### PR TITLE
GDB-7727 GraphDB becomes unresponsive when FedX repositories are used

### PR DESCRIPTION
**Pull request by MartinaDimova**
* Added warning in Create FedX Repo page for being an experimental feature.

### CODE REVIEW

**Comment by MartinaDimova** [comment]
Jenkins retry build

**Comment by MartinaDimova** [comment]
Jenkins retry build

**Review by desislava-hristova-ontotext — APPROVED** [review]

**Comment by MartinaDimova** [comment]
Jenkins retry build

**Comment by MartinaDimova** [comment]
Jenkins retry build

**Comment by MartinaDimova** [comment]
Jenkins retry build

**Pull request merged**
