### PR TITLE
GDB-7783 integrate save query action

### PR DESCRIPTION
**Pull request by svilenvelikov**
## What
Integrate the save query action from the ontotext yasgui component.

## Why
Save query action exists in current implementation in the GDB WB. It allows the user to complete the query name and the query itself, to select if the query will be private or public and save it.

## How
* The ontotext yasgui component now supports the save query action. This changes in this MR are related with the integration of the save action. See also the related branch https://github.com/Ontotext-AD/ontotext-yasgui/pull/39
* Implemented tests.

### CODE REVIEW

**Review by boyan-tonchev — APPROVED** [review]

**Review by boyan-tonchev — DISMISSED** [review]

**Comment by svilenvelikov** [comment]
Jenkins retry

**Comment by svilenvelikov** [comment]
Jenkins retry build

**Comment by svilenvelikov** [comment]
Jenkins retry build

**Comment by svilenvelikov** [comment]
Jenkins retry build

**Comment by svilenvelikov** [comment]
Jenkins retry build

**Review by boyan-tonchev — APPROVED** [review]

**Pull request merged**
